version: '3.8'
services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./static/uploads:/app/static/uploads
    environment:
      - ADMIN_USER=admin
      - ADMIN_PASS=МойСуперПароль123
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: p2p_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
